# Generated by Django 5.0.7 on 2024-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_gold", models.PositiveIntegerField(default=1000000000)),
                ("base_price", models.FloatField(default=1.0)),
            ],
        ),
    ]
