# Generated by Django 5.0.7 on 2024-07-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_gold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gold",
            old_name="base_price",
            new_name="gold_price",
        ),
    ]
